services:

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata

  employee-service:
    build: ./employee-service
    ports:
      - "7071:7071"
    depends_on:
      - oracle-db

  employee-address:
    build: ./employee-address
    ports:
      - "7072:7072"
    depends_on:
      - oracle-db

volumes:
  oracle-data: